name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:

  build:
    env: 
      platform: aws
      region: us-east-1
      account: example
    runs-on: ubuntu-latest

    steps:
      - name: "display Message"
        run: echo "hola Mundo"

      - name: "mostrando variables de entorno"
        run: |
          echo "Este es el valor de platform: ${{ env.platform}}"
          echo "Este es el valor de region: ${{ env.region}}"
          echo "Este es el valor de Account: ${{ env.account}}"



